include:
  - board: nice_nano_v2
    shield: cradio_left
    artifact-name: cradio-left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_FULL=y
  - board: nice_nano_v2
    shield: cradio_right
    artifact-name: cradio-right
  - board: seeeduino_xiao_ble
    shield: logos_left rgbled_adapter
    artifact-name: logos-left
    snippet: zmk-usb-logging
    #snippet: studio-rpc-usb-uart
    #cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: seeeduino_xiao_ble
    shield: logos_right rgbled_adapter
    artifact-name: logos-right
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
